// src/lib/dummyData.ts

export type Drink = {
  id: number;
  name: string;
  images: {
    cup: string;
    shadow: string;
    hero: string;
    ingredients: string;
  };
  type: 'Smoothie' | 'Crushed' | 'Juiced' | 'Blended';
  healthBenefits: ('< 200 Cal' | 'Low Gluten' | 'Low Fat' | 'Source of Protein' | 'Source of Fibre' | 'Dairy Free')[];
  ingredients: string[];
  nutrition: {
    servingSize: { med: string; ori: string; jnr: string };
    energy: string;
    energy_cal: string;
    protein: string;
    fatTotal: string;
    fatSaturated: string;
    carbohydrate: string;
    sugars: string;
    sodium: string;
    dietaryFibre: string;
  };
};

export const drinks: Drink[] = [
  {
    id: 1,
    name: "All Berry Bang",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/All-Berry-Bang_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/All-Berry-Bang_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/All-Berry-Bang_ingredients-1.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Gluten'],
    ingredients: ["Strawberry Yoghurt", "Blueberries", "Strawberries", "Apple Juice", "Raspberries", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1110 kJ",
      energy_cal: "262 cal",
      protein: "5.6 g",
      fatTotal: "3.7 g",
      fatSaturated: "2.5 g",
      carbohydrate: "54.3 g",
      sugars: "49.5 g",
      sodium: "116 mg",
      dietaryFibre: "0.8 g",
    },
  },
  {
    id: 2,
    name: "Banana Buzz",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Banana-Buzz_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Banana-Buzz_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Banana-Buzz_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Gluten'],
    ingredients: ["Milk", "Banana", "Honey", "Vanilla Yoghurt", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1620 kJ",
      energy_cal: "387 cal",
      protein: "17.0 g",
      fatTotal: "6.0 g",
      fatSaturated: "3.5 g",
      carbohydrate: "64.8 g",
      sugars: "58.1 g",
      sodium: "201 mg",
      dietaryFibre: "0.8 g",
    },
  },
  {
    id: 3,
    name: "Banana Mango Bling",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2019/09/Banana-Mango-Bling-cup-360x360-1.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2019/09/Banana-Mango-Bling-hero-360x360_FA2-1.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2019/09/Banana-Mango-Bling-ingredients-360x360-1.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Fat'],
    ingredients: ["Mango", "Banana", "Apple Juice", "Mango Nectar", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1260 kJ",
      energy_cal: "301 cal",
      protein: "3.8 g",
      fatTotal: "1.3 g",
      fatSaturated: "0.7 g",
      carbohydrate: "66.0 g",
      sugars: "57.0 g",
      sodium: "85 mg",
      dietaryFibre: "2.2 g",
    },
  },
  {
    id: 4,
    name: "Berry Crush",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Berry-Crush_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Berry-Crush_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Berry-Crush_ingredients.png",
    },
    type: 'Crushed',
    healthBenefits: ['Dairy Free'],
    ingredients: ["Raspberries", "Strawberries", "Apple Juice", "Crushed Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "640 kJ",
      energy_cal: "153 cal",
      protein: "1.1 g",
      fatTotal: "0.2 g",
      fatSaturated: "0.1 g",
      carbohydrate: "34.5 g",
      sugars: "32.0 g",
      sodium: "21 mg",
      dietaryFibre: "2.5 g",
    },
  },
  {
    id: 5,
    name: "Berry Remedy Juice",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2019/09/BERRY-REMEDY-Website-cup-360x360.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2019/09/BERRY-REMEDY-Website-hero-360x360_FA2-1.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2019/09/BERRY-REMEDY-Website-ingredients-360x360-v2.png",
    },
    type: 'Juiced',
    healthBenefits: ['Dairy Free'],
    ingredients: ["Blueberries", "Blackberries", "Apple", "Lemon", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "480 kJ",
      energy_cal: "115 cal",
      protein: "0.9 g",
      fatTotal: "0.3 g",
      fatSaturated: "0.1 g",
      carbohydrate: "25.6 g",
      sugars: "23.4 g",
      sodium: "9 mg",
      dietaryFibre: "1.8 g",
    },
  },
  {
    id: 6,
    name: "Blue Honolulu",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2021/06/MicrosoftTeams-image-1.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2021/06/MicrosoftTeams-image-2.jpg",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2021/06/MicrosoftTeams-image-3.jpg",
    },
    type: 'Smoothie',
    healthBenefits: ['Source of Protein'],
    ingredients: ["Milk", "Banana", "Vanilla Yoghurt", "Whey Protein", "Blue Spirulina", "Honey", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1580 kJ",
      energy_cal: "378 cal",
      protein: "23.0 g",
      fatTotal: "5.6 g",
      fatSaturated: "3.1 g",
      carbohydrate: "55.0 g",
      sugars: "45.2 g",
      sodium: "210 mg",
      dietaryFibre: "1.6 g",
    },
  },
  {
    id: 7,
    name: "Blueberry Blast",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Blueberry-Blast_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Blueberry-Blast_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Blueberry-Blast_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Fat'],
    ingredients: ["Blueberries", "Banana", "Apple Juice", "Vanilla Yoghurt", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1190 kJ",
      energy_cal: "284 cal",
      protein: "5.0 g",
      fatTotal: "2.1 g",
      fatSaturated: "1.3 g",
      carbohydrate: "57.2 g",
      sugars: "51.0 g",
      sodium: "98 mg",
      dietaryFibre: "2.9 g",
    },
  },
  {
    id: 8,
    name: "Brekkie to GoGo",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Brekkie-to-Go-Go_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Brekkie-to-Go-Go_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Brekkie-to-Go-Go_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Source of Protein'],
    ingredients: ["Milk", "Banana", "Honey", "Rolled Oats", "Vanilla Yoghurt", "Whey Protein", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1790 kJ",
      energy_cal: "428 cal",
      protein: "22.5 g",
      fatTotal: "7.4 g",
      fatSaturated: "3.9 g",
      carbohydrate: "68.3 g",
      sugars: "46.8 g",
      sodium: "205 mg",
      dietaryFibre: "5.1 g",
    },
  },
  {
    id: 9,
    name: "Caribbean Green",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Caribbean-Green_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Caribbean-Green_hero-1.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Caribbean-Green_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Dairy Free', 'Low Gluten', 'Low Fat'],
    ingredients: ["Pineapple", "Mango", "Banana", "Spinach", "Coconut Water", "Lime", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1010 kJ",
      energy_cal: "242 cal",
      protein: "3.6 g",
      fatTotal: "1.4 g",
      fatSaturated: "0.9 g",
      carbohydrate: "52.0 g",
      sugars: "43.8 g",
      sodium: "77 mg",
      dietaryFibre: "3.4 g",
    },
  },
  {
    id: 10,
    name: "Choc Muscle Hustle",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2019/09/CHOC-MUSCLE-HUSTLE-cup-360x360.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2019/09/CHOC-MUSCLE-HUSTLE-hero-360x360_FA2-1-1.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2019/09/CHOC-MUSCLE-HUSTLE-ingredients-360x360-v4.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Source of Protein'],
    ingredients: ["Milk", "Cocoa", "Chocolate Powder", "Whey Protein", "Banana", "Vanilla Yoghurt", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1900 kJ",
      energy_cal: "454 cal",
      protein: "28.0 g",
      fatTotal: "7.8 g",
      fatSaturated: "4.3 g",
      carbohydrate: "67.0 g",
      sugars: "55.0 g",
      sodium: "230 mg",
      dietaryFibre: "3.1 g",
    },
  },
  {
    id: 11,
    name: "Cookies & Creme",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2018/09/CookiesNCreme_Oreo_Cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2018/09/CookiesNCreme_HeroIngredient_v2.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2018/09/CookiesNCreme_Ingredients_v2.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Fat'],
    ingredients: ["Milk", "Vanilla Yoghurt", "Chocolate Cookies", "Cocoa", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1680 kJ",
      energy_cal: "402 cal",
      protein: "11.4 g",
      fatTotal: "8.1 g",
      fatSaturated: "4.5 g",
      carbohydrate: "70.5 g",
      sugars: "52.3 g",
      sodium: "260 mg",
      dietaryFibre: "2.2 g",
    },
  },
  {
    id: 12,
    name: "Energy Lift",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2016/12/Energy-Lift_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2016/12/Energy-Lift_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/01/Energy-Lift_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Fat'],
    ingredients: ["Banana", "Vanilla Yoghurt", "Skim Milk", "Honey", "Guarana Booster", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1320 kJ",
      energy_cal: "315 cal",
      protein: "12.0 g",
      fatTotal: "2.8 g",
      fatSaturated: "1.7 g",
      carbohydrate: "58.2 g",
      sugars: "49.0 g",
      sodium: "160 mg",
      dietaryFibre: "1.9 g",
    },
  },
  {
    id: 13,
    name: "Gym Junkie",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Gym-Junkie_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Gym-Junkie_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Gym-Junkie_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Gluten'],
    ingredients: ["Skim Milk", "Banana", "Vanilla Yoghurt", "Whey Protein", "Honey", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1500 kJ",
      energy_cal: "359 cal",
      protein: "25.0 g",
      fatTotal: "4.5 g",
      fatSaturated: "2.6 g",
      carbohydrate: "53.0 g",
      sugars: "45.5 g",
      sodium: "220 mg",
      dietaryFibre: "1.6 g",
    },
  },
  {
    id: 14,
    name: "King William Chocolate",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/King-William-Chocolate_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/King-William-Chocolate_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2016/12/King-William-Chocolate_ingredients-1.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Gluten'],
    ingredients: ["Milk", "Chocolate Powder", "Vanilla Yoghurt", "Banana", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1720 kJ",
      energy_cal: "411 cal",
      protein: "13.5 g",
      fatTotal: "6.2 g",
      fatSaturated: "3.6 g",
      carbohydrate: "73.0 g",
      sugars: "57.5 g",
      sodium: "210 mg",
      dietaryFibre: "2.6 g",
    },
  },
  {
    id: 15,
    name: "Mango Tango Crush",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Mango-Tango_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Mango-Tango_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Mango-Tango_ingredients.png",
    },
    type: 'Crushed',
    healthBenefits: ['Dairy Free'],
    ingredients: ["Mango Nectar", "Mango", "Passionfruit", "Crushed Ice", "Lemon"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "720 kJ",
      energy_cal: "172 cal",
      protein: "1.4 g",
      fatTotal: "0.4 g",
      fatSaturated: "0.2 g",
      carbohydrate: "39.5 g",
      sugars: "36.0 g",
      sodium: "24 mg",
      dietaryFibre: "1.9 g",
    },
  },
  {
    id: 16,
    name: "Passion Mango",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2016/12/Passion-Mango_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2016/12/Passion-Mango_hero-1.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Passion-Mango_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Fat'],
    ingredients: ["Mango", "Passionfruit", "Vanilla Yoghurt", "Banana", "Apple Juice", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1400 kJ",
      energy_cal: "335 cal",
      protein: "6.1 g",
      fatTotal: "3.2 g",
      fatSaturated: "2.0 g",
      carbohydrate: "69.0 g",
      sugars: "58.0 g",
      sodium: "110 mg",
      dietaryFibre: "2.3 g",
    },
  },
  {
    id: 17,
    name: "Protein Supreme",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Protein-Supreme_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Protein-Supreme_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Protein-Supreme_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Source of Protein'],
    ingredients: ["Skim Milk", "Whey Protein", "Banana", "Peanut Butter", "Vanilla Yoghurt", "Honey", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1980 kJ",
      energy_cal: "473 cal",
      protein: "33.0 g",
      fatTotal: "10.2 g",
      fatSaturated: "3.1 g",
      carbohydrate: "58.0 g",
      sugars: "44.0 g",
      sodium: "260 mg",
      dietaryFibre: "3.7 g",
    },
  },
  {
    id: 18,
    name: "Raspberry Ripe",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2016/12/Raspberry-Ripe_cup-1.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Raspberry-Ripe_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Raspberry-Ripe_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Fat'],
    ingredients: ["Raspberries", "Cocoa", "Coconut Milk", "Banana", "Apple Juice", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1360 kJ",
      energy_cal: "325 cal",
      protein: "4.5 g",
      fatTotal: "5.5 g",
      fatSaturated: "3.9 g",
      carbohydrate: "62.0 g",
      sugars: "50.0 g",
      sodium: "95 mg",
      dietaryFibre: "3.6 g",
    },
  },
  {
    id: 19,
    name: "Strawberry Squeeze",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Strawberry-Squeeze_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Strawberry-Squeeze_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Strawberry-Squeeze_ingredients.png",
    },
    type: 'Smoothie',
    healthBenefits: ['Low Gluten'],
    ingredients: ["Strawberries", "Apple", "Banana", "Strawberry Yoghurt", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "1230 kJ",
      energy_cal: "294 cal",
      protein: "5.8 g",
      fatTotal: "3.3 g",
      fatSaturated: "2.2 g",
      carbohydrate: "58.6 g",
      sugars: "50.1 g",
      sodium: "100 mg",
      dietaryFibre: "2.7 g",
    },
  },
  {
    id: 20,
    name: "Two & Five Juice",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Two-and-Five-Juice_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Two-and-Five-Juice_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2016/12/Two-and-Five-Juice_ingredients.png",
    },
    type: 'Juiced',
    healthBenefits: ['Low Gluten'],
    ingredients: ["Carrot", "Beetroot", "Celery", "Apple", "Orange", "Ginger", "Ice"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "510 kJ",
      energy_cal: "122 cal",
      protein: "2.0 g",
      fatTotal: "0.3 g",
      fatSaturated: "0.1 g",
      carbohydrate: "27.0 g",
      sugars: "23.0 g",
      sodium: "120 mg",
      dietaryFibre: "2.1 g",
    },
  },
  {
    id: 21,
    name: "Watermelon Crush",
    images: {
      cup: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Watermelon-Crush_cup.png",
      shadow: "https://www.boostjuice.com.au/img/cup_shadow.png",
      hero: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Watermelon-Crush_hero.png",
      ingredients: "https://www.boostjuice.com.au/wp-content/uploads/2017/02/Watermelon-Crush_ingredients.png",
    },
    type: 'Crushed',
    healthBenefits: ['Dairy Free'],
    ingredients: ["Fresh Watermelon", "Watermelon Juice", "Crushed Ice", "Lime"],
    nutrition: {
      servingSize: { ori: "610 mL", med: "450 mL", jnr: "350 mL" },
      energy: "360 kJ",
      energy_cal: "86 cal",
      protein: "0.9 g",
      fatTotal: "0.2 g",
      fatSaturated: "0.1 g",
      carbohydrate: "20.5 g",
      sugars: "18.5 g",
      sodium: "10 mg",
      dietaryFibre: "0.6 g",
    },
  },
];
